<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\..\utils\Primitives\Primitives.csproj" />
      <ProjectReference Include="..\DirectoryService.Contracts\DirectoryService.Contracts.csproj" />
      <ProjectReference Include="..\DirectoryService.Domain\DirectoryService.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation"  />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
      <PackageReference Include="Scrutor" />
      <PackageReference Include="CSharpFunctionalExtensions" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Locations\Commands\" />
      <Folder Include="Locations\Queries\" />
    </ItemGroup>

</Project>
